AGERA5_VARS = {
    "AGERA5-ET0-E": {
        "long_name": "Reference Evapotranspiration",
        "units": "mm/day",
        "source": "FAO56 with agERA5",
    },
    "AGERA5-ET0-D": {
        "long_name": "Reference Evapotranspiration",
        "units": "mm/dekad",
        "source": "FAO56 with agERA5",
    },
    "AGERA5-ET0-M": {
        "long_name": "Reference Evapotranspiration",
        "units": "mm/month",
        "source": "FAO56 with agERA5",
    },
    "AGERA5-ET0-A": {
        "long_name": "Reference Evapotranspiration",
        "units": "mm/year",
        "source": "FAO56 with agERA5",
    },
    "AGERA5-TMIN-E": {
        "long_name": "Minimum Air Temperature (2m)",
        "units": "K",
        "source": "agERA5",
    },
    "AGERA5-TMAX-E": {
        "long_name": "Maximum Air Temperature (2m)",
        "units": "K",
        "source": "agERA5",
    },
    "AGERA5-SRF-E": {
        "long_name": "Solar Radiation",
        "units": "J/m2/day",
        "source": "agERA5",
    },
    "AGERA5-WS-E": {"long_name": "Wind Speed", "units": "m/s", "source": "agERA5"},
    "AGERA5-RH06-E": {
        "long_name": "Relative humidity at 06h (local time, 2m)",
        "units": "%",
        "source": "agERA5",
    },
    "AGERA5-RH09-E": {
        "long_name": "Relative humidity at 09h (local time, 2m)",
        "units": "%",
        "source": "agERA5",
    },
    "AGERA5-RH12-E": {
        "long_name": "Relative humidity at 12h (local time, 2m)",
        "units": "%",
        "source": "agERA5",
    },
    "AGERA5-RH15-E": {
        "long_name": "Relative humidity at 15h (local time, 2m)",
        "units": "%",
        "source": "agERA5",
    },
    "AGERA5-RH18-E": {
        "long_name": "Relative humidity at 18h (local time, 2m)",
        "units": "%",
        "source": "agERA5",
    },
    "AGERA5-PF-E": {
        "long_name": "Precipitation",
        "units": "mm/day",
        "source": "agERA5",
    },
    "AGERA5-PF-D": {
        "long_name": "Precipitation",
        "units": "mm/dekad",
        "source": "agERA5",
    },
    "AGERA5-PF-M": {
        "long_name": "Precipitation",
        "units": "mm/month",
        "source": "agERA5",
    },
    "AGERA5-PF-A": {
        "long_name": "Precipitation",
        "units": "mm/year",
        "source": "agERA5",
    },
}

WAPOR3_VARS = {
    "L1-AETI-A": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/year",
    },
    "L1-AETI-D": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/day",
    },
    "L1-AETI-M": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/month",
    },
    "L1-E-A": {"long_name": "Evaporation", "units": "mm/year"},
    "L1-E-D": {"long_name": "Evaporation", "units": "mm/day"},
    "L1-GBWP-A": {"long_name": "Gross Biomass Water Productivity", "units": "kg/m³"},
    "L1-I-A": {"long_name": "Interception", "units": "mm/year"},
    "L1-I-D": {"long_name": "Interception", "units": "mm/day"},
    "L1-NBWP-A": {"long_name": "Net Biomass Water Productivity", "units": "kg/m³"},
    "L1-NPP-D": {"long_name": "Net Primary Production", "units": "gC/m²/day"},
    "L1-NPP-M": {"long_name": "Net Primary Production", "units": "gC/m²/month"},
    "L1-PCP-A": {"long_name": "Precipitation", "units": "mm/year"},
    "L1-PCP-D": {"long_name": "Precipitation", "units": "mm/day"},
    "L1-PCP-E": {"long_name": "Precipitation", "units": "mm/day"},
    "L1-PCP-M": {"long_name": "Precipitation", "units": "mm/month"},
    "L1-QUAL-LST-D": {"long_name": "Quality Land Surface Temperature", "units": "d"},
    "L1-QUAL-NDVI-D": {
        "long_name": "Quality of Normalized Difference Vegetation Index",
        "units": "d",
    },
    "L1-RET-A": {"long_name": "Reference Evapotranspiration", "units": "mm/year"},
    "L1-RET-D": {"long_name": "Reference Evapotranspiration", "units": "mm/day"},
    "L1-RET-E": {"long_name": "Reference Evapotranspiration", "units": "mm/day"},
    "L1-RET-M": {"long_name": "Reference Evapotranspiration", "units": "mm/month"},
    "L1-RSM-D": {"long_name": "Relative Soil Moisture", "units": "%"},
    "L1-T-A": {"long_name": "Transpiration", "units": "mm/year"},
    "L1-T-D": {"long_name": "Transpiration", "units": "mm/day"},
    "L1-TBP-A": {"long_name": "Total Biomass Production", "units": "kg/ha"},
    "L2-AETI-A": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/year",
    },
    "L2-AETI-D": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/day",
    },
    "L2-AETI-M": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/month",
    },
    "L2-E-A": {"long_name": "Evaporation", "units": "mm/year"},
    "L2-E-D": {"long_name": "Evaporation", "units": "mm/day"},
    "L2-GBWP-A": {"long_name": "Gross Biomass Water Productivity", "units": "kg/m³"},
    "L2-I-A": {"long_name": "Interception", "units": "mm/year"},
    "L2-I-D": {"long_name": "Interception", "units": "mm/day"},
    "L2-NBWP-A": {"long_name": "Net Biomass Water Productivity", "units": "kg/m³"},
    "L2-NPP-D": {"long_name": "Net Primary Production", "units": "gC/m²/day"},
    "L2-NPP-M": {"long_name": "Net Primary Production", "units": "gC/m²/month"},
    "L2-QUAL-NDVI-D": {
        "long_name": "Quality of Normalized Difference Vegetation Index",
        "units": "d",
    },
    "L2-RSM-D": {"long_name": "Relative Soil Moisture", "units": "%"},
    "L2-T-A": {"long_name": "Transpiration", "units": "mm/year"},
    "L2-T-D": {"long_name": "Transpiration", "units": "mm/day"},
    "L2-TBP-A": {"long_name": "Total Biomass Production", "units": "kg/ha"},
    "L3-AETI-A": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/year",
    },
    "L3-AETI-D": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/day",
    },
    "L3-AETI-M": {
        "long_name": "Actual EvapoTranspiration and Interception",
        "units": "mm/month",
    },
    "L3-E-A": {"long_name": "Evaporation", "units": "mm/year"},
    "L3-E-D": {"long_name": "Evaporation", "units": "mm/day"},
    "L3-GBWP-A": {"long_name": "Gross Biomass Water Productivity", "units": "kg/m³"},
    "L3-I-A": {"long_name": "Interception", "units": "mm/year"},
    "L3-I-D": {"long_name": "Interception", "units": "mm/day"},
    "L3-NBWP-A": {"long_name": "Net Biomass Water Productivity", "units": " kg/m³"},
    "L3-NPP-D": {"long_name": "Net Primary Production", "units": "gC/m²/day"},
    "L3-NPP-M": {"long_name": "Net Primary Production", "units": "gC/m²/month"},
    "L3-QUAL-NDVI-D": {
        "long_name": "Quality of Normalized Difference Vegetation Index",
        "units": "d",
    },
    "L3-RSM-D": {"long_name": "Relative Soil Moisture", "units": "%"},
    "L3-T-A": {"long_name": "Transpiration", "units": "mm/year"},
    "L3-T-D": {"long_name": "Transpiration", "units": "mm/day"},
    "L3-TBP-A": {"long_name": "Total Biomass Production", "units": "kg/ha"},
}
